### ISSUE TITLE
No transmit after hours of operation

### ISSUE THREAD

**Issue by peros550** [pbendersky/ir-esp-uart#2]
Hi Pablo, 

I have used your code to create an A/C accessory to be used with homekit. The esp device I use is a Wemos D1 mini. 

Everything works fine just after I connect the device to power. It's very reliable compared to the previous version no word about that. All commands are received by the A/C 100% reliably. 

The reason I'm opening this topic is because I'm getting some very strange behavior after a few hours or days of operation. This happens randomly and when I try to send commands nothing happens. It just does not send anything. I can't blame the electronics because as I said it works very reliably after a restart. Also, the rest part of the code responds normally providing feedback to Home app. 

Have you noticed anything similar in your case? Any ideas for me to troubleshoot further would be very welcome :)

**Comment by pbendersky** [comment]
I haven't noticed this behaviour... I do get occasional "No Response" errors for the accessory, but haven't seen the IR failing to send.
